apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels: 
    svc2pod: web
spec:
  containers:
  - name: nginx
    image: nginx:1.17.6-alpine
    # リソースの制限を定義しないと警告が発生
    resources:
      limits: 
        memory: 512Mi
        cpu: "1"
    ports:
    - name: http
      containerPort: 80
