apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    svc2pod: web
  ports:
  - port: 80
    targetPort: http
    # 外部から接続するときのポート番号指定
    nodePort: 30100
  # ノード外部から接続できるサービスタイプ。※ClusterIPはポッド間通信のみ。LoadBalancerはノード外部から接続できロードバランサー機能もある。
  type: NodePort
